apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  create-topics.sh: |
    #!/bin/bash
    {{- range .Values.topics }}
    kafka-topics.sh --create --topic {{ .name }} \
      --bootstrap-server {{ $.Values.kafka.brokerUrl }} \
      --partitions {{ .partitions }} \
      --replication-factor {{ .replicationFactor }}
    {{- end }}
