{{- if .Values.subConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-crawl-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.subConsumer.minReplicas }}
  strategy:
    type: {{ .Values.strategy.type | default "RollingUpdate" }}
  selector:
    matchLabels:
      app: sub-crawl-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: sub-crawl-{{ .Chart.Name }}
    spec:
      # 컨테이너 구동 시 토픽 생성 (overwrite x)
      initContainers:
      - name: init-create-topics
        image: "{{ .Values.subConsumer.image.repository }}:{{ .Values.subConsumer.image.tag }}"
        imagePullPolicy: {{ .Values.subConsumer.image.pullPolicy }}
        command: [ "/bin/bash", "/scripts/create-topics.sh" ]
        volumeMounts:
          - name: init-scripts
            mountPath: /scripts
      containers:
      - name: sub-crawl-{{ .Chart.Name }}
        image: "{{ .Values.subConsumer.image.repository }}:{{ .Values.subConsumer.image.tag }}"
        imagePullPolicy: {{ .Values.subConsumer.image.pullPolicy }}
        env:
        - name: KAFKA_BROKER
          value: "{{ .Values.kafka.brokerUrl }}"
        - name: CONSUMER_GROUP
          value: "{{ .Values.subConsumer.groupId }}"
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        command: ["/bin/bash", "-c", "ciftag kafka sub common"]
        volumeMounts:
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:  # 로컬 볼륨 마운트이므로 로컬 노드에서만 사용 가능. ebs의 경우 별도 방식
      - name: init-scripts
        configMap:
          name: {{ .Chart.Name }}-config
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}