{{- if .Values.agtConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agt-crawl-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mainConsumer.replicas }}
  selector:
    matchLabels:
      app: agt-crawl-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: agt-crawl-{{ .Chart.Name }}
    spec:
      containers:
      - name: agt-crawl-{{ .Chart.Name }}
        image: "{{ .Values.agtConsumer.image.repository }}:{{ .Values.agtConsumer.image.tag }}"
        imagePullPolicy: {{ .Values.agtConsumer.image.pullPolicy }}
        env:
        - name: KAFKA_BROKER
          value: "{{ .Values.kafka.brokerUrl }}"
        - name: CONSUMER_GROUP
          value: "{{ .Values.agtConsumer.groupId }}"
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        command: ["/bin/bash", "-c", "ciftag kafka agt common"]
        volumeMounts:
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:  # 로컬 볼륨 마운트이므로 로컬 노드에서만 사용 가능. ebs의 경우 별도 방식
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
