apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: main-crawl-{{ .Chart.Name }} # 메인 컨슈머를 기본으로 서비스
  ports:
  - protocol: TCP
    port: 9092               # Kafka 기본 포트
    targetPort: 9092         # 컨슈머 컨테이너의 포트
