apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  labels:
    app: {{ .Chart.Name }}-web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      nodePort: {{ .Values.service.web.nodePort }}
  selector:
    app: {{ .Chart.Name }}-web
