apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: api-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        - containerPort: 5555
        env:
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
#        command: ["supervisord -c /etc/supervisord.conf"]
        command: ["/bin/bash", "-c", "sleep infinity"]
        volumeMounts:
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:  # 로컬 볼륨 마운트이므로 로컬 노드에서만 사용 가능. ebs의 경우 별도 방식
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      # 노드 설정 관련
      # nodeSelector: {{ .Values.nodeSelector }}
      # tolerations: {{ .Values.tolerations }}
      # affinity: {{ .Values.affinity }}
